spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver

mopl:
  account:
    password-policy: "no"
    temp-password-policy: "random"
    temp-password-reset-timeout-policy: "get"
